name: "Test Action"
description: "Report new TS errors"
inputs:
  user-id:
    description: "User ID"
    required: true
  token:
    description: "Token"
    required: true
  github-token:
    description: "Github Token - https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#about-the-github_token-secret"
    required: true
outputs:
  errors-list:
    description: "New errors to report"
runs:
  using: "node16"
  main: "dist/index.js"
