name: "Test Action"
description: "Report new TS errors"
inputs:
  user-id:
    description: "User ID"
    required: true
  token:
    description: "Token"
    required: true
outputs:
  errors-list:
    description: "New errors to report"
runs:
  using: "node16"
  main: "dist/index.js"
